### ISSUE TITLE
Mouse problem.

### ISSUE THREAD

**Issue by DeveleruxMemphis** [JernejL/samp-map-editor#8]
I have at the same problem -> https://github.com/JernejL/samp-map-editor/issues/2
Just I have desktop PC not laptop.
I select object in editor and select another object in close. How to fix this?
I have Windows 7 but I have the same problem in Win10.
Please help me, and sorry I have bad english skills.
Have a nice day!

**Comment by JernejL** [comment]
duplicate issue of #2 like you said yourself - do not open duplicate issues, it's annoying and redundant.
